version: '3.3'
services:
  service1:
    build:
      context: /vip/wfile/Zhaoxi.AspNetCore31.DockerProject
    image: composecore31v4.3
    ports:
      - 8081:80/tcp
  service2:
    image: composecore31v4.3
    ports:
      - 8082:80/tcp
    command: ["dotnet", "/app/Zhaoxi.AspNetCore31.DockerProject.dll"]
  nginx:
    image: nginx:latest
    ports:
      - 8086:80/tcp
    volumes:
      - /vip/wnginx/nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:6.0
    ports:
      - 8085:6380/tcp
    volumes:
      - /vip/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /vip/redis/data:/data:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]